create or replace PACKAGE UTILS
AS
    PROCEDURE VER_LOCALIDADES (V_LOCATION OUT SYS_REFCURSOR);
END;
/
create or replace NONEDITIONABLE PACKAGE BODY UTILS
AS
    PROCEDURE VER_LOCALIDADES (V_LOCATION OUT SYS_REFCURSOR)
    AS
    BEGIN
        OPEN V_LOCATION FOR SELECT * FROM LOCALIDAD;
    END;

END;
