create or replace PACKAGE ESTADISTICA
AS
    PROCEDURE CANT_DEPTOS (V_CANT OUT NUMBER);
END;

/

create or replace PACKAGE BODY ESTADISTICA
AS
    PROCEDURE CANT_DEPTOS (V_CANT OUT NUMBER)
    AS
    BEGIN
        SELECT COUNT(*) INTO V_CANT FROM DEPARTAMENTO;
    END;
END;