ALTER SESSION SET nls_date_format='DD/MM/YYYY';
----**** DROPS TABLES ****---
DROP TABLE SERVICIO;

DROP TABLE PAGO;

DROP TABLE CHECKOUT;

DROP TABLE CHECKIN;

DROP TABLE RESERVA;

DROP TABLE TRANSPORTE;

DROP TABLE TOUR;

DROP TABLE INVENTARIO;

DROP TABLE DEPARTAMENTO;

DROP TABLE CONDUCTOR;

DROP TABLE USUARIO;

DROP TABLE ROL;

DROP TABLE PRODUCTO;

DROP TABLE TERMINAL;

DROP TABLE LOCALIDAD;

----**** DROPS SEQUENCES ***------

DROP SEQUENCE ROL_AUTO;

DROP SEQUENCE PRODUCTO_AUTO;

DROP SEQUENCE LOCALIDAD_AUTO;

DROP SEQUENCE TERMINAL_AUTO;

DROP SEQUENCE TRANSPORTE_AUTO;

DROP SEQUENCE TOUR_AUTO;

DROP SEQUENCE SERVICIO_AUTO;

DROP SEQUENCE INVENTARIO_AUTO;

DROP SEQUENCE RESERVA_AUTO;

DROP SEQUENCE DEPARTAMENTO_AUTO;

DROP SEQUENCE CONDUCTOR_AUTO;

DROP SEQUENCE USUARIO_AUTO;
---**** PRODUCT ****----
CREATE SEQUENCE PRODUCTO_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUCTO(
    ID NUMBER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(60) NOT NULL,
    PRECIO NUMBER NOT NULL,
    CANTIDAD_INICIAL NUMBER,
    IS_DEFAULT NUMBER DEFAULT 0
);

--**** TABLE ROL ****---
CREATE SEQUENCE ROL_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE ROL(
    ID NUMBER NOT NULL PRIMARY KEY,
    CARGO VARCHAR2(60) NOT NULL
);

--**** TABLE LOCATION ****-----

CREATE SEQUENCE LOCALIDAD_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE LOCALIDAD(
    ID NUMBER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2(60)
);

--**** TABLE USER ****---
CREATE SEQUENCE USUARIO_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE USUARIO(
    ID NUMBER PRIMARY KEY,
    RUT VARCHAR2(10) NOT NULL UNIQUE,
    NOMBRE VARCHAR2(60) NOT NULL,
    APELLIDO VARCHAR2(60) NOT NULL,
    IMAGEN CLOB,
    CORREO VARCHAR2(60) UNIQUE NOT NULL,
    ESTADO NUMBER DEFAULT 0,
    DIRECCION VARCHAR2(60) NOT NULL,
    TELEFONO VARCHAR2(60) NOT NULL,
    PASS VARCHAR2(60) NOT NULL,
    ID_ROL NUMBER NOT NULL,
    
    CONSTRAINT FK_ROL_ID FOREIGN KEY(ID_ROL) REFERENCES ROL (ID)
);

--**** TABLE DRIVER ****---
CREATE SEQUENCE CONDUCTOR_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE CONDUCTOR (
    ID NUMBER PRIMARY KEY NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    VEHICULO VARCHAR2(60) NOT NULL,
    PATENTE VARCHAR(8) NOT NULL,
    ID_LOCALIDAD NUMBER NOT NULL,
    CONSTRAINT FK_ID_USUARIO_CONDUCTOR FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID),
    CONSTRAINT FK_ID_LOCALIDAD_CONDUCTOR FOREIGN KEY(ID_LOCALIDAD) REFERENCES LOCALIDAD (ID)
);


--**** TABLE DEPARTAMENT ****--

CREATE SEQUENCE DEPARTAMENTO_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE DEPARTAMENTO(
    ID NUMBER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(60) NOT NULL,
    NUMERO_BANNO NUMBER NOT NULL,
    NUMERO_HABITACION NUMBER NOT NULL,
    DIRECCION VARCHAR2(60) NOT NULL,
    VALOR_ARRIENDO NUMBER NOT NULL,
    ESTADO NUMBER DEFAULT 1,
    ID_LOCALIDAD NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(60),
    ESTADO_DISPONIBLE CHAR NOT NULL,
    ESTADO_RESERVA CHAR NOT NULL,
    IMAGENES CLOB,    
    ADDED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_DATE DATE DEFAULT SYSDATE,    
    CONSTRAINT FK_ID_LOCALIDAD FOREIGN KEY(ID_LOCALIDAD) REFERENCES LOCALIDAD (ID)
);

CREATE OR REPLACE
TRIGGER DEPARTAMENTO_UPDATE 
BEFORE UPDATE ON DEPARTAMENTO FOR EACH row 
BEGIN 
    :new.MODIFIED_DATE := SYSDATE;
END;
/
---**** TABLE INVENTARY ****---
CREATE SEQUENCE INVENTARIO_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE INVENTARIO(
    ID NUMBER NOT NULL PRIMARY KEY,
    ID_DEPARTAMENTO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    ESTADO NUMBER DEFAULT 0,
    DESCRIPCION VARCHAR2(200) DEFAULT 'Nuevo',
    COSTO_REPARACION NUMBER DEFAULT 0,
    ADDED_DATE TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO (ID),
    CONSTRAINT FK_ID_DEPARTAMENTO FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID)
);

CREATE OR REPLACE
TRIGGER INVENTARIO_UPDATE 
BEFORE UPDATE ON INVENTARIO FOR EACH row 
BEGIN 
    :new.MODIFIED_DATE := SYSDATE;
END;
/

--**** TABLE TERMINALES ****--

CREATE SEQUENCE TERMINAL_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE TERMINAL(
    ID NUMBER PRIMARY KEY,
    ID_LOCALIDAD NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_ID_LOCALIDAD_TERMINAL FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDAD (ID)
);

--**** TABLE TRANSPORT ****--

CREATE SEQUENCE TRANSPORTE_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE TRANSPORTE(
    ID VARCHAR2(5) NOT NULL PRIMARY KEY,
    ID_CONDUCTOR NUMBER NOT NULL,
    ID_TERMINAL NUMBER NOT NULL,
    FECHA VARCHAR2(10) NOT NULL,
    HORARIO VARCHAR2(12) NOT NULL,
    PRECIO NUMBER NOT NULL,
    ESTADO NUMBER DEFAULT 1,
    CONSTRAINT FK_ID_CONDUCTOR FOREIGN KEY(ID_CONDUCTOR) REFERENCES CONDUCTOR (ID),
    CONSTRAINT FK_ID_TERMINAL FOREIGN KEY (ID_TERMINAL) REFERENCES TERMINAL (ID)
    
);

--**** TABLE TOUR ****--
CREATE SEQUENCE TOUR_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE TOUR(
    ID VARCHAR2(5) NOT NULL PRIMARY KEY,
    CUPO NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    FECHA VARCHAR2 (60) NOT NULL,
    HORA_INICIO VARCHAR2 (60) NOT NULL,
    DURACION VARCHAR2 (60) NOT NULL,    
    DESCRIPCION VARCHAR2(60),
    IMAGENES CLOB,
    ESTADO NUMBER DEFAULT 1,
    ID_LOCALIDAD NUMBER NOT NULL,
    CONSTRAINT FK_ID_LOCALIDAD_TOUR FOREIGN KEY(ID_LOCALIDAD) REFERENCES LOCALIDAD(ID)
);

----**** TABLE CHECKOUT ****--
CREATE SEQUENCE RESERVA_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE RESERVA(
    ID NUMBER NOT NULL PRIMARY KEY,
    FECHA_INICIO VARCHAR2(10) NOT NULL,
    DIAS NUMBER NOT NULL,
    CANTIDAD_PERSONA NUMBER,
    TOTAL_RESERVA NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    ID_DEPARTAMENTO NUMBER NOT NULL,
    ESTADO NUMBER DEFAULT 0,
    ADDED_DATE TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES USUARIO(ID),
    CONSTRAINT FK_ID_DEPARTAMENTO_RESERVA FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID)
);
CREATE OR REPLACE
TRIGGER RESERVA_UPDATE 
BEFORE UPDATE ON RESERVA FOR EACH row 
BEGIN 
    :new.MODIFIED_DATE := SYSDATE;
END;
/

--**** TABLE CKECKIN ****--

CREATE TABLE CHECKIN(
    ID NUMBER NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR2(60),
    PAGO_COMPLETADO NUMBER DEFAULT 0,    
    ADDED_DATE TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_ID_CHECKIN_RESERVA FOREIGN KEY(ID) REFERENCES RESERVA(ID)
);

CREATE OR REPLACE
TRIGGER CHECKIN_UPDATE 
BEFORE UPDATE ON DEPARTAMENTO FOR EACH row 
BEGIN 
    :new.MODIFIED_DATE := SYSDATE;
END;
/
--**** TABLE CHECKOUT ****--

CREATE TABLE CHECKOUT(
    ID NUMBER NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR2(60),
    INCONVENIENTES NUMBER,
    ESTADO NUMBER,
    ADDED_DATE TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_DATE  TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_ID_CHECKOUT_RESERVA FOREIGN KEY(ID) REFERENCES RESERVA(ID)
);

CREATE OR REPLACE
TRIGGER CHECKOUT_UPDATE
BEFORE UPDATE ON DEPARTAMENTO FOR EACH row 
BEGIN 
    :new.MODIFIED_DATE := SYSDATE;
END;
/
--**** TABLE PAY ****--

CREATE TABLE PAGO(
    ID NUMBER NOT NULL PRIMARY KEY,
    ABONO NUMBER,
    PAGO_TOTAL NUMBER DEFAULT 0,
    PAGO_INCONVENIENTE NUMBER DEFAULT 0,
    ADDED_DATE TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_ID_PAGO_RESERVA FOREIGN KEY(ID) REFERENCES RESERVA(ID)
);

CREATE OR REPLACE
TRIGGER PAGO_UPDATE 
BEFORE UPDATE ON DEPARTAMENTO FOR EACH row 
BEGIN 
    :new.MODIFIED_DATE := SYSDATE;
END;
/


--**** TABLE SERVICE ****--
CREATE SEQUENCE SERVICIO_AUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE SERVICIO(
    ID NUMBER NOT NULL PRIMARY KEY,
    FECHA_CONTRATO DATE NOT NULL,
    DESCRIPCION VARCHAR2(60),
    ID_RESERVA NUMBER NOT NULL,
    ID_TRANSPORTE VARCHAR2(5) NULL,
    ID_TOUR VARCHAR2(5) NULL,
    CONSTRAINT FK_ID_RESERVA FOREIGN KEY(ID_RESERVA) REFERENCES RESERVA(ID),
    CONSTRAINT FK_ID_TRANSPORTE_SERVICIO FOREIGN KEY(ID_TRANSPORTE) REFERENCES TRANSPORTE(ID),
    CONSTRAINT FK_ID_TOUR_SERVICIO FOREIGN KEY(ID_TOUR) REFERENCES TOUR(ID)
);

--------------------------------------------------------------------------------------
INSERT INTO ROL VALUES(ROL_AUTO.NEXTVAL,'Administrador');

INSERT INTO ROL VALUES(ROL_AUTO.NEXTVAL,'Funcionario');

INSERT INTO ROL VALUES(ROL_AUTO.NEXTVAL,'Cliente');

INSERT INTO ROL VALUES(ROL_AUTO.NEXTVAL,'Conductor');
--------------------------------------------------------------------------------------
INSERT INTO PRODUCTO VALUES(PRODUCTO_AUTO.NEXTVAL,'Silla comedor',35000,6,1);

INSERT INTO PRODUCTO VALUES(PRODUCTO_AUTO.NEXTVAL,'Mesa comedor',500000,1,1);

INSERT INTO PRODUCTO VALUES(PRODUCTO_AUTO.NEXTVAL,'Cama 2 Plazas',210000,1,1);

INSERT INTO PRODUCTO VALUES(PRODUCTO_AUTO.NEXTVAL,'Lampara sala de estar',25000,2,1);

INSERT INTO PRODUCTO VALUES(PRODUCTO_AUTO.NEXTVAL,'Cama 1 Plaza',180000,2,1);

--------------------------------------------------------------------------------------
INSERT INTO LOCALIDAD VALUES(LOCALIDAD_AUTO.NEXTVAL,'La Serena');

INSERT INTO LOCALIDAD VALUES(LOCALIDAD_AUTO.NEXTVAL,'Puerto Varas');

INSERT INTO LOCALIDAD VALUES(LOCALIDAD_AUTO.NEXTVAL,'Pucón');

INSERT INTO LOCALIDAD VALUES(LOCALIDAD_AUTO.NEXTVAL,'Viña del Mar');

--------------------------------------------------------------------------------------

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, IMAGEN, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO) 
VALUES(USUARIO_AUTO.NEXTVAL,'18937755-K','Claudio','Abele','https://img.freepik.com/foto-gratis/chico-worldface-espanol-fondo-blanco_53876-137665.jpg?w=360','CAbele@admin.cl','Antonio Baras 132','9-12345678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','1',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, IMAGEN, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'20141805-4','Nicolas','Castillo','https://img.freepik.com/foto-gratis/chico-worldface-espanol-fondo-blanco_53876-137665.jpg?w=360','NCastillo@Funcionario.cl','General Bonilla 123','9-12345678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','2',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'20134605-4','Gabriela','Shivali','GShivali@Funcionario.cl','Pasaje Las Termas 1537','9-12123678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','2',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'20148636-4','Hanna','Asabe','HAsabe@Funcionario.cl','Condominio Aurora 1131','9-12345324','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','2',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, IMAGEN, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'21234325-2','Diego','Pavez','https://img.freepik.com/foto-gratis/chico-worldface-espanol-fondo-blanco_53876-137665.jpg?w=360','test@duocuc.cl','LA CASA DEL','9-12345678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','3',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'20234325-2','Fabian','Cezara','FCezara@gmail.cl','General Baquedano 123','9-12341234','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','3',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'18234325-6','Daniels','Jakov','DJakov@gmail.cl','Avenida Pacifica 489','9-15645128','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','3',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'19234325-6','Lutgarde','Klytaimnestra','LKlytaimnestra@gmail.cl','Coronoel Sanders 198','9-12346712','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','3',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'20624325-2','Sabina','Miloslav','SMiloslav@gmail.cl','Pasaje Estrada 231','9-67945678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','3',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'16234325-2','Rose','Milles','RMilles@gmail.cl','Condominio Las Rosas 241','9-12345421','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','3',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, IMAGEN, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'17234654-2','Conductor','Test','https://img.freepik.com/foto-gratis/chico-worldface-espanol-fondo-blanco_53876-137665.jpg?w=360','conductor@Chofer.cl','Las palmeras 1241','9-12345678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','4',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'15344653-2','Darina','Durward','DDurward@Chofer.cl','Coronel Estrada 345','9-12345678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','4',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'17346434-2','Alex','Siena','ASiena@Chofer.cl','Condominio Las Estelas 1224','9-12345678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','4',1);

INSERT INTO USUARIO (ID,RUT, NOMBRE, APELLIDO, CORREO, DIRECCION, TELEFONO, PASS, ID_ROL, ESTADO)
VALUES(USUARIO_AUTO.NEXTVAL,'16526434-2','Paulina','Matti','PMatti@Chofer.cl','Condominio Las Estrellas 2141','9-12345678','$2b$10$1WKLtNaU8/hRbINDgMPBJuiyXp3Nhos1W/lVEl3xkJM9TL3N5aUWq','4',1);

-------------------------------------------------------------------------------------
INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Edificio Padre Hurtado',1,2,'AV. Vespucio 305',72990,1,'Departamento Básico','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Edificio Las Palmas',2,3,'Calle Almagro 8322',72990,1,'Departamento Básico','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Condomio Paraiso Sur',3,2,'Calle Medalla 3942',72990,4,'Departamento Basico','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Condomio Las Estrellas',2,3,'Nueva Zelanda 342',98990,2,'Departamento Intermedio','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Recinto El Hospedaje',4,3,'AV. Coronel 232',120990,3,'Departamento Completo','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Recinto Sur 3',2,3,'Calle Mongoles 3322',98990,4,'Departamento Intermedio','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Recinto Estela 2',3,4,'Calle La Plata 2442',98990,3,'Departamento Intermedio','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Condominio Rio Claro 1',2,4,'Calle Estela 1321',120990,1,'Departamento Completo','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Recinto Brisa 3',3,4,'Calle Estrada 2312',120990,2,'Departamento Completo','Y','Y','');

INSERT INTO DEPARTAMENTO (ID,NOMBRE,NUMERO_BANNO,NUMERO_HABITACION,DIRECCION,VALOR_ARRIENDO,ID_LOCALIDAD,DESCRIPCION,ESTADO_DISPONIBLE,ESTADO_RESERVA,IMAGENES)
VALUES(DEPARTAMENTO_AUTO.NEXTVAL,'Edificio Los Sauces',3,4,'Calle Las Asacias 3322',120990,4,'Departamento Completo','Y','Y','');

--------------------------------------------------------------------------------------

INSERT INTO CONDUCTOR VALUES(CONDUCTOR_AUTO.NEXTVAL,11,'CAMIONETA','44-SD-E3',1);
INSERT INTO CONDUCTOR VALUES(CONDUCTOR_AUTO.NEXTVAL,12,'CAMIONETA','D5-RD-E3',2);
INSERT INTO CONDUCTOR VALUES(CONDUCTOR_AUTO.NEXTVAL,13,'CAMIONETA','DS-69-E5',3);
INSERT INTO CONDUCTOR VALUES(CONDUCTOR_AUTO.NEXTVAL,14,'CAMIONETA','D4-SD-E3',4);
-- --------------------------------------------------------------------------------------
INSERT INTO INVENTARIO (ID,ID_DEPARTAMENTO,ID_PRODUCTO,CANTIDAD) VALUES(INVENTARIO_AUTO.NEXTVAL,1,2,2);
INSERT INTO INVENTARIO (ID,ID_DEPARTAMENTO,ID_PRODUCTO,CANTIDAD) VALUES(INVENTARIO_AUTO.NEXTVAL,1,1,2);
INSERT INTO INVENTARIO (ID,ID_DEPARTAMENTO,ID_PRODUCTO,CANTIDAD) VALUES(INVENTARIO_AUTO.NEXTVAL,2,3,2);

--------------------------------------------------------------------------------------
INSERT INTO TERMINAL VALUES(TERMINAL_AUTO.NEXTVAL,1,'TERMINAL DE LA SERENA');
INSERT INTO TERMINAL VALUES(TERMINAL_AUTO.NEXTVAL,2,'TERMINAL DE PUERTO VARAS');
INSERT INTO TERMINAL VALUES(TERMINAL_AUTO.NEXTVAL,3,'TERMINAL DE PÚCON');
INSERT INTO TERMINAL VALUES(TERMINAL_AUTO.NEXTVAL,4,'TERMINAL DE VIÑA DEL MAR');
--------------------------------------------------------------------------------------
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'10/12/2022','11:00','5 HORAS','PLAYA BONITA',1,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'22/12/2022','12:00','3 HORAS','SENDERISMO',1,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'12/12/2022','15:00','2 HORAS','RAFTIN',1,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'23/12/2022','17:00','5 HORAS','ESCALADA',2,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'12/12/2022','21:00','4 HORAS','PLAYA BONITA2',2,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'23/12/2022','21:30','6 HORAS','ESCALADA',2,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'12/12/2022','22:00','5 HORAS','ESCALADA',3,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'23/12/2022','22:30','5 HORAS','SENDERISMO',3,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'23/12/2022','23:00','7 HORAS','TERMAS',4,'');
INSERT INTO TOUR (ID,CUPO,PRECIO,FECHA,HORA_INICIO,DURACION,DESCRIPCION,ID_LOCALIDAD,IMAGENES) VALUES('TO_'||TO_CHAR(TOUR_AUTO.NEXTVAL),3,7500,'23/12/2022','23:30','5 HORAS','RAFTIN',4,'');


COMMIT;

CREATE OR REPLACE TRIGGER UPDATETOUR
BEFORE UPDATE OF CUPO ON TOUR
FOR EACH ROW

DECLARE

BEGIN

  IF :NEW.CUPO = 0 THEN
    :NEW.ESTADO := 0;
  END IF;
END;
/